### ISSUE TITLE
Add ability to create a place

### ISSUE THREAD

**Issue by thektan** [thektan/taste#9]
## Todo
- [x] Setup WeDeploy data
- [x] Add a "Create Place" page
- [x] Add a button go to a create place page (This will show at the end of the search results after the user begins typing in the search field as a "Can't find what you're looking for? Add the place yourself here!")
- [x] Add place page which will show basic information

## Form Fields
- Name (Required)
- Address (Required)
- Tags
- Phone Number
- Website
- Yelp Link

Duplicates are ok for name and location.

## Resources

~For location autocomplete we can use: https://community.algolia.com/places/examples.html~ From the demo, it doesn't autocomplete addresses very well and it's missing a lot of locations.

- For form: https://github.com/jaredpalmer/formik
- For category input: https://github.com/JedWatson/react-select
- Place autocomplete: https://www.mapbox.com/

**Comment by thektan** [comment]
To get form data try using https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

**Comment by thektan** [comment]
Look into this as well: https://github.com/jaredpalmer/formik

**Comment by thektan** [comment]
Completed and in master
